### ISSUE TITLE
EPIC: <Initial Install>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/level_up_loot_vt#1]
### Description

- [ ] install django, django-allauth
- [ ] create env.py file, hide secret key, hide database url
- [ ] install fixtures files
