### ISSUE TITLE
EPIC: <User Profiles>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/level_up_loot_vt#5]
### Allow Users to create/update/manage and delete user profiles

- [ ]  Allow user create profile
- [ ] Allow user update profile
- [ ] Allow user delete profile
