### ISSUE TITLE
EPIC: <Adding Products to Cart>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/level_up_loot_vt#6]
### Create an app to allow users to view products and add them to a cart

- [ ] Create Database models, template, form and fixtures for viewing products
- [ ] Allow user/admin to add products to a cart
- [ ] Allow user/admin to update/delete products from their cart
