### ISSUE TITLE
EPIC: <Purchasing Items>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/level_up_loot_vt#7]
### Allow users to purchase items in their cart

- [ ] Create Database models, template, form for a checkout app
- [ ] Install Stripe
- [ ] Create Webhooks for Stripe
- [ ] Give User feedback that their purchase has been made
