### ISSUE TITLE
EPIC: <Front End Design>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/level_up_loot_vt#8]
### Description

- [ ] Create Templates for each app
- [ ] Create an overall branding/design for the store
- [ ] Have a Responsive Design across the site
