### ISSUE TITLE
EPIC: <Error Pages>

### ISSUE THREAD

**Issue by VictoriaT87** [VictoriaT87/level_up_loot_vt#9]
### Create custom error page templates for 404, 403 and 500 errors.

- [ ] Create 404.html Page
- [ ] Create 403.html Page
- [ ] Create 500.html Page
